version: '3.8'

services:
  # Database
  mongo:
    image: mongo
    container_name: bb_mongo
    logging:
      driver: none
    ports:
      - "27018:27017"
    volumes:
      - bored_bot_db_data:/data/db

  # provides a UI to edit things in mongodb
  # just navigate to localhost:4321
  mongo-gui:
    image: ugleiton/mongo-gui
    container_name: bb_mongo_gui
    restart: always
    logging:
      driver: none
    ports:
      - "4321:4321"
    environment:
      - MONGO_URL=mongodb://mongo:27017

volumes:
  bored_bot_db_data: